project:
  type: website
  output-dir: docs

website:
  title: "Design of Experiments"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Prerequisites"
        href: stat_concepts.qmd
      - text: "Introduction to DOE" 
        href: doe.qmd
      - text: "External links"
        href: summary.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-title: On this page 
    css: styles.css  # Add a custom CSS file (optional)